name: Train Cat-Dog Model

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  train-model:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set lowercase image name
      run: echo "LOWERCASE_IMAGE_NAME=$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Pull the latest Docker image
      run: docker pull ${{ env.REGISTRY }}/${{ env.LOWERCASE_IMAGE_NAME }}:version-01

    - name: Train the model
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/data:/app/data \
          -v ${{ github.workspace }}/logs:/app/logs \
          ${{ env.REGISTRY }}/${{ env.LOWERCASE_IMAGE_NAME }}:version-01 \
          python src/train.py experiment=catdog_ex trainer.max_epochs=5 model.base_model=resnet18 +trainer.log_every_n_steps=5

    - name: Check accuracy
      run: |
        latest_run=$(ls -td ${{ github.workspace }}/logs/train/runs/* | head -n 1)
        accuracy=$(grep -oP 'val/acc": \K[0-9.]+' $latest_run/metrics.json | tail -n 1)
        echo "Final validation accuracy: $accuracy"
        if (( $(echo "$accuracy < 0.95" | bc -l) )); then
          echo "Accuracy is below 95%. Failing the workflow."
          exit 1
        fi

    - name: Upload model checkpoint
      uses: actions/upload-artifact@v3
      with:
        name: model-checkpoint
        path: ${{ github.workspace }}/logs/train/runs/*/checkpoints/
        if-no-files-found: error

    - name: Upload training logs
      uses: actions/upload-artifact@v3
      with:
        name: training-logs
        path: ${{ github.workspace }}/logs/train/runs/*/
        if-no-files-found: error

    - name: Upload config
      uses: actions/upload-artifact@v3
      with:
        name: config
        path: ${{ github.workspace }}/logs/train/runs/*/.hydra/
        if-no-files-found: error